### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by xcodebuild** [agilecreativity/source2pdf#1]
```
/usr/lib64/ruby/gems/2.1.0/gems/minitar-0.5.4/lib/archive/tar/minitar.rb:905:in `stat': No such file or directory @ rb_file_s_stat - examples/calculator.lua.xhtml (Errno::ENOENT)
        from /usr/lib64/ruby/gems/2.1.0/gems/minitar-0.5.4/lib/archive/tar/minitar.rb:905:in `pack_file'
        from /usr/lib64/ruby/gems/2.1.0/gems/agile_utils-0.2.3/lib/agile_utils/file_util.rb:32:in `block in tar_gzip_files'
        from /usr/lib64/ruby/gems/2.1.0/gems/agile_utils-0.2.3/lib/agile_utils/file_util.rb:31:in `each'
        from /usr/lib64/ruby/gems/2.1.0/gems/agile_utils-0.2.3/lib/agile_utils/file_util.rb:31:in `tar_gzip_files'
        from /usr/lib64/ruby/gems/2.1.0/gems/vim_printer-0.2.5/lib/vim_printer/cli.rb:117:in `execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/vim_printer-0.2.5/lib/vim_printer/cli.rb:32:in `print'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/lib64/ruby/gems/2.1.0/gems/source2pdf-0.2.4/lib/source2pdf/source2pdf.rb:42:in `files_to_htmls'
        from /usr/lib64/ruby/gems/2.1.0/gems/source2pdf-0.2.4/lib/source2pdf/exporter.rb:93:in `files2htmls'
        from /usr/lib64/ruby/gems/2.1.0/gems/source2pdf-0.2.4/lib/source2pdf/exporter.rb:41:in `export'
        from /usr/lib64/ruby/gems/2.1.0/gems/source2pdf-0.2.4/lib/source2pdf/cli.rb:36:in `export'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/lib64/ruby/gems/2.1.0/gems/source2pdf-0.2.4/bin/source2pdf:6:in `<top (required)>'
        from /usr/bin/source2pdf.ruby2.1:23:in `load'
        from /usr/bin/source2pdf.ruby2.1:23:in `<main>'
```

In fact,there is no `examples/calculator.lua.*x*html` `examples/calculator.lua.html`

How to slove it?

**Comment by agilecreativity** [comment]
Sorry for the late response, I have updated the gem to the latest version that should fix this issue. Please report the issue if you still found the error. This should have been fixed.
